### ISSUE TITLE
Add Installation section 

### ISSUE THREAD

**Issue by lfarah** [caloon/UnsupportedOSVersionAlert#4]
The `README.md`, which lacks an `Installation Section`.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an `Installation Section`
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by caloon** [comment]
Added Installation section and restructered the Readme.md. Feedback is much appreciated :)
